Write to file instead of terminal

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -59,23 +59,31 @@ jobs:
           ORG_GRADLE_PROJECT_geysermcPassword: ${{ secrets.DEPLOY_PASS }}
         
       - name: Get Version
-        if: ${{ (success() || failure()) && github.repository == 'GeyserMC/Geyser' }}
+        if: ${{ (success() || failure()) && github.repository == 'lukeeey/Geyser' }}
         id: get-version
         run: |
           version=$(cat gradle.properties | grep -o "version=[0-9\\.]*" | cut -d"=" -f2)
           echo "VERSION=${version}" >> $GITHUB_OUTPUT
 
       - name: Get Supported Minecraft Versions
-        if: ${{ (success() || failure()) && github.repository == 'GeyserMC/Geyser' }}
+        if: ${{ (success() || failure()) && github.repository == 'lukeeey/Geyser' }}
         id: get-minecraft-versions
         run: |
-          JSON=$(java -jar bootstrap/standalone/build/libs/Geyser-Standalone.jar --print-minecraft-versions | grep -m1 '^{')
-          JSON_B64=$(echo "$JSON" | base64 -w 0)
-          echo "MINECRAFT_VERSIONS_JSON=$JSON_B64" >> $GITHUB_OUTPUT
+          set -e
+
+          java -jar bootstrap/standalone/build/libs/Geyser-Standalone.jar --dump-minecraft-versions
+
+          if [ ! -f mcversions.json ]; then
+            echo "mcversions.json not found"
+            exit 1
+          fi
+
+          JSON_B64=$(base64 -w 0 mcversions.json)
+          echo "MINECRAFT_VERSIONS_JSON=$JSON_B64" >> "$GITHUB_OUTPUT"
 
       - name: Get Release Metadata
-        if: ${{ (success() || failure()) && github.repository == 'GeyserMC/Geyser' }}
-        uses: GeyserMC/actions/release@master
+        if: ${{ (success() || failure()) && github.repository == 'lukeeey/Geyser' }}
+        uses: lukeeey/actions/release@master
         id: metadata
         with:
           appID: ${{ secrets.RELEASE_APP_ID }}
